FROM python:3.11-slim

RUN addgroup --system app && adduser --system --group app

WORKDIR /home/app

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

RUN apt-get update && apt-get install -y netcat-openbsd && rm -rf /var/lib/apt/lists/*
RUN pip install --upgrade pip
COPY requirements.txt .
RUN pip install -r requirements.txt

COPY . .

RUN mkdir -p /home/app/static/media
RUN chown -R app:app /home/app
USER app

ENTRYPOINT ["/home/app/entrypoint.prod.sh"]
