name: tests

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build and run dev
      run: |
        docker compose up -d --build
        sleep 10
        curl http://localhost:5010
